repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.1
    hooks:
    - id: sqlfluff-lint
      name: sqlfluff-lint
      entry: sqlfluff lint --config dbt-pre-commit-conf/.sqlfluff models/
      description: "Lints sql files with `SQLFluff`"
      additional_dependencies : ['dbt-core==1.7.10', 'dbt-extractor==0.5.1', 'dbt-bigquery==1.7.6', 'dbt-trino==1.7.1', 'sqlfluff-templater-dbt==3.0.1']